### ISSUE TITLE
Return of the Bookmarklet

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#10]
@markmacgillivray has said that "Regarding the old bookmarklet, this should fit with what Steve is doing for the new extension, so that most of it can be used as a bookmarklet too."

If possible, I'd be happy to dedicate a bit of extra time here if it generated a bookmarklet too. Then we get all the cross-compatibility again!

**Comment by JosephMcArthur** [comment]
@Steven-Eardley can let me know if this is possible? If so, assign it a milestone.

**Comment by markmacgillivray** [comment]
Working on this. Even if it cannot be automatically generated, the bookmarklet / widgets will follow the new plugin functionality and style, which is now testable in a web page without installing the plugin

**Comment by JosephMcArthur** [comment]
Issue moved to [OAButton/backend #262](https://github.com/OAButton/backend/issues/262) via [**ZenHub**](https://www.zenhub.com/)
