### ISSUE TITLE
Instruction page to be seen after first login 

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#12]
_From @JosephMcArthur on October 16, 2014 16:43_

Mock up and copy here. https://www.dropbox.com/s/op8brcfcfmsap7p/Screenshot%202014-10-16%2017.42.46.png?dl=0

_Copied from original issue: OAButton/oab-chromeaddon#19_

**Comment by markmacgillivray** [comment]
Instruction page is now on account page on the site, and users are sent there on first login of plugin anyway now, so the instructions in the button are no longer necessary. This also gives us one source of instructions to manage, and different plugin / bookmarklet / widgets can point there.
