### ISSUE TITLE
Making "We want a story" more obvious

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#15]
_From @mtb-za on December 8, 2014 15:1_

I had a chat with someone who missed that we want a story from people when logging a paywall in the Chrome app. How can we make it more obvious that the reason that the "I didn't get access" button needs a story? Any thoughts?

_Copied from original issue: OAButton/oab-chromeaddon#30_

**Comment by JosephMcArthur** [comment]
_From @andylolz on December 8, 2014 15:24_

Do you need a story? If so, why? I can’t see how they’re used on the website at the moment, so it’s not clear to me why you’d ask.

Demonstrate how the stories are used, and people will populate this.

**Comment by JosephMcArthur** [comment]
_From @kynan on December 9, 2014 11:5_

+1 in particular on @andylolz' 2nd point.

**Comment by Steven-Eardley** [comment]
Is this a site issue or a plugin issue? Currently the text **"Please finish the sentence above. This will be sent to the author."** is all we have to show the story's purpose.

**Comment by JosephMcArthur** [comment]
This is a plugin issue, but it's with quite an old version. It should be easy to close with a new UI, but we need to nail down the UI first.

**Comment by markmacgillivray** [comment]
This issue is fixed in the new plugin in that it will not accept a request until something has been typed into the story box. Then it links straight away to the new request, opens it, and encourages the user to go there. The backend will also send a followup email. So this issue can be closed from the plugin perspective now.
