### ISSUE TITLE
Add "I can't find an email" function to ODB plug-in

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#16]
_From @JosephMcArthur on March 3, 2016 17:15_

This would allow us to hunt down an email later, but still allow people to request. Could give the status "email needed"

_Copied from original issue: OAButton/odb#36_

**Comment by Steven-Eardley** [comment]
Would you need a checkbox by the email field, or should the field just be optional rather than required? The latter option would likely lead to more requests spuriously missing emails.

**Comment by JosephMcArthur** [comment]
I'd suggest checkbox. If we were fancy, we could make it look optional and
if they try to submit without it give them a choice.

**Comment by JosephMcArthur** [comment]
@markmacgillivray sounds like this is no longer in the plugin. Are we good to close?

**Comment by JosephMcArthur** [comment]
Issue moved to [OAButton/backend #266](https://github.com/OAButton/backend/issues/266) via [**ZenHub**](https://www.zenhub.com/)
