### ISSUE TITLE
Keep plugin open when people click off screen

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#17]
_From @JosephMcArthur on March 6, 2016 20:55_

Seems like (at least with people needing to manually grab the email) this is going to be an issue. Users certainly seem to struggle with it, which is causing duplicate blocks. Especially where the plugin doesn't grab the article title. 

_Copied from original issue: OAButton/odb#46_

**Comment by JosephMcArthur** [comment]
_From @Steven-Eardley on March 7, 2016 11:41_

Unfortunately, it [isn't possible](https://developer.chrome.com/extensions/faq#faq-persist-popups) to simply make the popup persist:

> ##### Can extensions keep popups open after the user clicks away from them?
No, popups automatically close when the user focuses on some portion of the browser outside of the popup. There is no way to keep the popup open after the user has clicked away.

I propose two possible solutions:
* Keep the button as as popup, but keep track of the state as it is used - allow the user to click off and back on to fill all details. Keeping track of the state will prevent duplicate blocks.
 - The disruption of this can be minimised by better metadata scraping (currently no effort is made with emails)
* The button could operate from a tab, rather than a popup. I think this would be more annoying to use.

Bonus idea (much harder to do reliably)
* inject a side-bar type div for the button into the article's page, allowing it to persist during page interaction.

**Comment by JosephMcArthur** [comment]
_From @markmacgillivray on March 7, 2016 11:46_

Yep a tab would be annoying - may as well just open up the website, in that
case.

A sidebar div is possible - true, there may be some pages on which the
behaviour of it may not be as expected, but it can be made fairly reliable
by not making it actually a sidebar but making it a fixed content on the
top right of the page with a z-index of 10000000 so it sits on top of
everything else.

**Comment by JosephMcArthur** [comment]
How hard is this to implement now? 

> Keep the button as as popup, but keep track of the state as it is used - allow the user to click off and back on to fill all details. Keeping track of the state will prevent duplicate blocks.
> The disruption of this can be minimised by better metadata scraping (currently no effort is made with emails)

**Comment by JosephMcArthur** [comment]
_From @markmacgillivray on March 7, 2016 14:29_

It is not that hard but takes time we don't have this week at least. And in
addition, if we keep throwing in fixes without stopping and rewriting, we
will just continue fighting small issues from now until the end of time.
For now, this is the way it is. Now we have stability to plan work going
forward, we can put it into a milestone for a future (soon) release.

**Comment by JosephMcArthur** [comment]
_From @dhimmel on April 9, 2016 20:41_

> Keep the button as as popup, but keep track of the state as it is used - allow the user to click off and back on to fill all details. Keeping track of the state will prevent duplicate blocks.

Currently, there are three fields in a request. Copy & paste can only populate a single field. So essentially the popup is unusable until state memory is enabled.

> The button could operate from a tab, rather than a popup. I think this would be more annoying to use.

In general, I don't like having to install an extension because it's a hassle and requires granting undesirable permissions. So I'd favor a migration to a webservice.

**Comment by markmacgillivray** [comment]
This issue is solved in that the new plugin process is more automated, and the user has less interaction. It will still disappear if they click off, but they no longer need to go searching about the page, so should not click off until after submitting their story (or deciding they don't want to submit one). Email is now collected via the backend and where failing the user is prompted to go looking for one and then enter it into the request on the website, which will be created anyway, with a status of "email needed", allowing other people to provide emails if they know it (or our own people to go looking for them).
