### ISSUE TITLE
Make ODB understand PubMed article pages

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#18]
_From @rossmounce on March 6, 2016 20:54_

I just tried to ODB this page: http://www.ncbi.nlm.nih.gov/pubmed/25543783
My Citeulike bookmarklet usually gets PubMed pages like this where the DOI of the article is clearly displayed. I assume Mendeley and others do too.

_Copied from original issue: OAButton/odb#45_

**Comment by Steven-Eardley** [comment]
This functionality will be moved to the back-end, so effort will be focused there to achieve this goal.

**Comment by markmacgillivray** [comment]
Closing this one, no longer related to plugin.

**Comment by JosephMcArthur** [comment]
Can we move it, I know this is something people want for requesting Data?

**Comment by markmacgillivray** [comment]
The backend will be able to understand pubmed pages anyway, we have already
previously parsed them. We have more complex issues with PLOS and
sciencedirect pages now, which may result in simplification of what data we
bother trying to parse, as a uniform experience may be better. But yeah can
move it to backend if you like.

**Comment by JosephMcArthur** [comment]
So, when you say "will be", do you mean this can just be closed because
it's done?

**Comment by markmacgillivray** [comment]
It is done in the backend dev version, yes. So the plugin will just get
pubmed metadata too, when it starts talking to the new backend to create
requests. So there is certainly nothing further to do from the plugin
perspective. From the backend it is still being tested before deployment,
but will be live before the next plugin version is released.

**Comment by JosephMcArthur** [comment]
Okay, so good to close before moving as it'll be in the next release.
