### ISSUE TITLE
Simplified signup pages in the plugins

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#2]
Use the website for sign-up - the plugins should only require a valid API key pasted from the website.

**Comment by Steven-Eardley** [comment]
The authentication page is now at the extension options, as recommended by chrome, accessed via the extensions management page:

<img width="455" alt="screen shot 2016-07-04 at 12 32 02" src="https://cloud.githubusercontent.com/assets/1446355/16559242/8bac74d2-41e3-11e6-9dc7-d73cca54a482.png">

@JosephMcArthur - As you can see, it needs some tidying up and making pretty - we'll get around to that. If you have any preference of what the text should say, please comment in this issue.

**Comment by JosephMcArthur** [comment]
Looks good. After this page, can we have it go to an "instructions page". This would close #12 

Immediate thoughts on text are that:
- [ ] Let's not call it an API key. Maybe Account Key or similar.
- [ ] Does that link go to /account? 
- [ ] Should probably note that they need to sign up somewhere

**Comment by markmacgillivray** [comment]
This will become obsolete in the new plugin - unregistered users will be able to use the plugin to check availability, but prompted to sign up to do more. Signing up will automatically save their api key to their plugin, or for users who sign up and then get the plugin, the first time they use it it will ask them to go to their account page to get signed in. The user will not have to do anything beyond click the link, and sign in on the web page if they have not already done so. The plugin then updates the account page so we know we don't have to tell them how to get their plugin. I will close this now, although this functionality is not actually deployed yet, it is encompassed in ongoing work.
