### ISSUE TITLE
Use Inline install for Chrome

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#20]
Described here: https://developer.chrome.com/webstore/inline_installation

**Comment by Steven-Eardley** [comment]
Can-do. There are some extra steps required (e.g. getting the ID of it once its loaded into the web store, verifying site ownership) but these aren't too onerous.

**Comment by Steven-Eardley** [comment]
The code is written for this, should be available alongside the other major changes. Need to add a few lines to the site, but installation can continue conventionally alongside.

**Comment by JosephMcArthur** [comment]
Sounds like @markmacgillivray has this in new version.

**Comment by JosephMcArthur** [comment]
Issue moved to [OAButton/backend #265](https://github.com/OAButton/backend/issues/265) via [**ZenHub**](https://www.zenhub.com/)
