### ISSUE TITLE
Bookmarklet instructions page to be seen after first log in

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#22]
_From @JosephMcArthur on October 16, 2014 16:43_

Mock up and copy here. https://www.dropbox.com/s/op8brcfcfmsap7p/Screenshot%202014-10-16%2017.42.46.png?dl=0

_Copied from original issue: OAButton/backend#34_

**Comment by markmacgillivray** [comment]
Don't think we need this here. The instructions are now on the site /account page and users are directed there for their instructions now. So will close as not an extension or bookmarklet issue any more.
