### ISSUE TITLE
Unit tests for essential API requests

### ISSUE THREAD

**Issue by Steven-Eardley** [OAButton/unified-extension#23]
Keep track of things breaking at either end. To consider:

* these spurious requests will need to be identified and discarded to avoid polluting the dataset

**Comment by Steven-Eardley** [comment]
See https://github.com/OAButton/backend/issues/165#issuecomment-232775024

**Comment by markmacgillivray** [comment]
This can be closed as not relevant to the extension. API is tested via the backend. Plugin can do nothing about them being unavailable anyway, so no use unit testing them within the plugin.
