### ISSUE TITLE
Streamlined UI

### ISSUE THREAD

**Issue by JosephMcArthur** [OAButton/unified-extension#3]
The UI could be cleaner. Credentials via chrome style options page, simplify the main UI, respond to what information the API returns.

Jumping off point: https://docs.google.com/presentation/d/1mJv7rMnQUXzvJzDmAIo3JDZJFi9e5eg8eoYwFo2SzEE/edit#slide=id.g100df090a1_0_36

**Comment by markmacgillivray** [comment]
Covered in the new version coming soon
