### ISSUE TITLE
Unifying the OA and OD Buttons

### ISSUE THREAD

**Issue by Steven-Eardley** [OAButton/unified-extension#8]
How do we switch between open access / open data button requests? Ideas:

* depend on what the API returns - give option for what is not currently available.
* checkbox vs 'fork in the road' - allowing users to only request either or at final stage.
* ask this question first, every time the user opens the button.

Note: this has repercussions across the website etc.

**Comment by Steven-Eardley** [comment]
But for now, continue on a course where the codebase is shared but we generate an OA or OB.

**Comment by markmacgillivray** [comment]
Or could check status against both, and offer to create request for
whichever has nothing to return.

**Comment by JosephMcArthur** [comment]
This is close to what we were discussing Mark. The user would be presented with two buttons with two potential states. A article button which either gave you a click (from /use) through to the article or asked you to make a request - and the same for data. 

These buttons, if the user clicked them, could take you to search first (e.g scholar) to "check" before sending.

**Comment by markmacgillivray** [comment]
Closing this one, new plugin will offer info about data, articles, and anything else we add on the backend. scholar search to be kicked off from request page for better feedback capability. This issue is no longer needed.
